name: CI

on:
  push:
    branches-ignore: [deploy]
    paths:
      - "lib/**"
      - "t/**"
      - "Makefile.PL"
      - ".github/workflows/ci.yml"
  pull_request:
    branches: [main]
    paths:
      - "lib/**"
      - "t/**"
      - "Makefile.PL"
  workflow_dispatch:
    inputs:
      perl-version:
        required: false
        type: string
  workflow_call:
    inputs:
      perl-version:
        required: false
        type: string

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      perl-version: ${{ steps.vars.outputs.perl-version }}
    steps:
    - name: Checkout code to determine the minimum supported perl version
      if: ${{ inputs.perl-version == '' }}
      uses: actions/checkout@v3
      with:
        repository: pkgcraft/pkgcraft-perl

    - name: Set perl versions to test against
      id: vars
      run: |
        if [[ -n "${{ inputs.perl-version }}" ]]; then
          echo "perl-version=$(jq 'split(",")' -Rc <(echo '${{ inputs.perl-version }}'))" >> $GITHUB_OUTPUT
        else
          min_ver=$(sed -rn "/^\s*MIN_PERL_VERSION / s/.*=> '([0-9](.[0-9]+)*)',/\1/p" Makefile.PL)
          if [[ -n ${min_ver} ]]; then
            echo "perl-version=['${min_ver}', '5']" >> $GITHUB_OUTPUT
          else
            exit 1
          fi
        fi

  test:
    needs: setup
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        perl-version: ${{ fromJson(needs.setup.outputs.perl-version) }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        repository: pkgcraft/pkgcraft-perl
        submodules: true

    - name: Download prebuilt pkgcraft-c library
      id: download-artifact
      uses: dawidd6/action-download-artifact@v2
      with:
        github_token: ${{ secrets.PKGCRAFT_CI_TOKEN }}
        repo: pkgcraft/pkgcraft-c
        branch: main
        workflow: ci.yml
        name: pkgcraft-c-${{ runner.os }}
        path: pkgcraft

    - name: Set up Perl ${{ matrix.perl-version }}
      uses: shogo82148/actions-setup-perl@v1
      id: perl
      with:
        perl-version: ${{ matrix.perl-version }}
        enable-modules-cache: false

    - name: Set up cache
      uses: actions/cache@v3
      with:
        path: local
        key: ${{ github.job }}-${{ runner.os }}-perl-${{ steps.perl.outputs.perl-version }}-${{ hashFiles('Makefile.PL') }}
        restore-keys: ${{ github.job }}-${{ runner.os }}-perl-${{ steps.perl.outputs.perl-version }}-

    - name: Install deps
      run: |
        perl Makefile.PL
        cpanm -L local --installdeps .

    - name: Build and test module
      run: |
        make
        make test
