name: lint

on:
  push:
    branches-ignore: [deploy]
    paths:
      - "**/*.pl"
      - "**/*.pm"
      - "**/*.t"
      - ".github/workflows/lint.yml"
  pull_request:
    branches: [main]
    paths:
      - "**/*.pl"
      - "**/*.pm"
      - "**/*.t"

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Perl
      uses: shogo82148/actions-setup-perl@v1
      id: perl
      with:
        perl-version: 5
        install-modules-with: cpanm
        install-modules-args: -n
        install-modules: Perl::Tidy

    - name: Run perltidy
      shell: bash
      run: |
        shopt -s extglob globstar nullglob
        perltidy --pro=.../.perltidyrc -b -bext='/' **/*.p[lm] **/*.t && git diff --exit-code
